version: '3.4'


# Common Django template for Geonode, Celery services below
x-common-django:
  &default-common-django
  image: goatcommunity/spcgeonode:django-3.2
  environment:
    - DEBUG=True
  volumes:
    - ../../:/spcgeonode/
    - ./_volume_static:/spcgeonode-static/
    - ./_volume_media:/spcgeonode-media/

services:
  django:
    << : *default-common-django
    command: "uwsgi --chdir=/spcgeonode --module=geonode.wsgi --socket=:8000 --http=127.0.0.1:8001 --processes=5 --py-autoreload=2"
  celery:
    << : *default-common-django
    command: 'celery -A geonode.celery_app:app worker --without-gossip --without-mingle -Ofair -B -E --statedb=/spcgeonode-static/worker.state -s /spcgeonode-static/celerybeat-schedule --loglevel=ERROR --concurrency=10 -n worker1@%h'

  nginx:
    image: goatcommunity/spcgeonode:nginx-3.2
    volumes:
      - ./_volume_static:/spcgeonode-static/
      - ./_volume_media:/spcgeonode-media/
      - ./_volume_certificates:/spcgeonode-certificates/

  geoserver:
    image: goatcommunity/spcgeonode:geoserver-3.2
    volumes:
      - ./_volume_geodatadir:/spcgeonode-geodatadir/

  letsencrypt:
    image: goatcommunity/spcgeonode:letsencrypt-3.2
    volumes:
      - ./_volume_certificates:/spcgeonode-certificates/

  pgdumper_nogeo:
    image: goatcommunity/spcgeonode:pgdumper-3.2
    volumes:
      - ./_volume_pgdumps:/spcgeonode-pgdumps/

  pgdumper_geo:
    image: goatcommunity/spcgeonode:pgdumper-3.2
    volumes:
      - ./_volume_pgdumps:/spcgeonode-pgdumps/

  rclone:
    image: goatcommunity/spcgeonode:rclone-3.2
    volumes:
      - ./_volume_pgdumps:/spcgeonode-pgdumps/
      - ./_volume_media:/spcgeonode-media/
      - ./_volume_geodatadir:/spcgeonode-geodatadir/

  postgres:
    ports:
      - "5432:5432"
